## Application data.
#
# All entries are of the following form:
# Application name: - name of the application
#    package: package name - used for launching and stopping an app on the watch
#    activity: activity name - used for launching an app on the watch
#    keepOnly: [action1,] - list of action to be considered in simulation
#    actions: - yaml list of action specifications
#       action1 : [instruction11,] - list of instruction to perform the action
#       action2 : [instruction21,] - list of instruction to perform the action
#         ...


# Agenda:
#   package: com.google.android.wearable.app
#   activity: com.google.android.clockwork.home.calendar.EventListActivity2
#   keepOnly: [open]  # Action to be selected starting at 1.
#   actions :
#     open: ["(open_app, 20)"]
#     force-stop: ["(force_stop, 20)"]

Alarm:
  package: com.google.android.deskclock
  activity: com.google.android.deskclock.AlarmGatewayActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

# ASB:
#   package: nz.co.asb.asbmobile
#   activity: nz.co.asb.wear.MainActivity
#   keepOnly: [open] []
#   actions:
#     open: ["(open_app, 20)"]
#     force-stop: ["(force_stop, 20)"]

AppInTheAir:
  package: com.aita
  activity: com.aita.mainscreen.MainActivity
  keepOnly: [open]
  actions:
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

AthkarOfPrayer:
  package: com.appsforall.athkaralsalah
  activity: com.appsforall.athkaralsalah.MainActivityWear
  keepOnly: [open]
  actions:
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    openAndClose: ["(open_app, 20)", "(close_app, 5)"]
    switchTabAndScrollDown: ["(click((260, 30)), 0)", "(swipe_up, 17)"]

Battery:
  package: com.huawei.watch.supersavepower
  activity: com.huawei.watch.supersavepower.view.BatteryActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Bring:
  package:  ch.publisheria.bring
  activity: ch.publisheria.bring.activities.BringWearMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    addRandomItem: ["(click((150,80)), 0)", "(click((150,80)), 0)"]

# Health
Calm:
  package: com.calm.android
  activity: com.calm.android.activities.MainWearActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    seePersonalData: ["(click((250, 50)), 20)"]
    clickOnSunIcon: ["(click((200, 260)), 20)"]  # Subscription required
    clickOnMoonIcon: ["(click((300, 260)), 20)"]  # Subscription required

Camera:
  package: com.google.android.GoogleCamera
  activity: com.google.android.apps.camera.wear.wearappv2.WearCameraActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

ChinaDaily:
  package: com.chinadaily.wear
  activity: com.chinadaily.NewsHomeActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Citymapper:
  package: com.citymapper.app.release
  activity: com.citymapper.app.wear.EntryActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


# Contacts:
#   package: com.google.android.wearable.app
#   activity: com.google.android.clockwork.home.contacts.ContactsActivity
#   keepOnly: [open]  # Action to be selected starting at 1.
#   actions :
#     open: ["(open_app, 20)"]
#     force-stop: ["(force_stop, 20)"]

DailyTracking:
  package : com.huawei.health
  activity: com.huawei.bone.view.dailytrack.activity.DailyTrackMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    openAndClose: ["(open_app, 20)", "(close_app, 5)"]
    # 2 First use
    logIn: ["(open_app, 5)", "(swipe_right, 1)", "(swipe_right, 1)", "(swipe_right, 1)", "(swipe_right, 1)", "(swipe_right, 1)", "(click((190,190)), 5)", "(close_app, 3)"]
    # 3 Open, scroll down and close
    scrollDown: ["(open_app, 5)", "(swipe_down, 1)", "(swipe_down, 1)", "(swipe_down, 1)", "(close_app, 5)"]
    # 4 Open VO2Max
    VO2Max: ["(open_app, 5)", "(swipe_right, 1)", "(click((150,190)), 3)", "(close_app, 3)"]
    # 5 Open BMI
    BMI: ["(open_app, 5)", "(swipe_right, 1)", "(click((250,190)), 3)", "(close_app, 3)"]


DCLMRadio:
  package: org.dclm.live
  activity: .MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    openAndClose: ["(open_app, 20)", "(close_app, 5)"]
    # 2. Listen to the radio 10 seconds
    listenToRadio15sec: ["(click((95, 190)), 15)"]
    listenToRadioAndBackgroung: ["(open_app, 8)", "(click((95, 190)), 12)", "(background, 5)"]

DiabetesM:
  package: com.mydiabetes
  activity: com.mydiabetes.MainActivity
  keepOnly: [open, addInsulin, addCarbs, addGlucose, addCal, addProt, addFat]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force-stop, 20)"]
    addGlucose: ["(swipe_left, 0)",  "(click((190,55)), 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]
    addInsulin: ["(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((190,55)), 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]
    addCarbs: ["(swipe_left, 0)", "(swipe_left, 0)",  "(click((190,55)), 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((117,32)), 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]
    addCal: ["(swipe_left, 0)", "(swipe_left, 0)", "(click((40,190)), 0)", "(click((190,55)), 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]
    addProt: ["(swipe_left, 0)", "(swipe_left, 0)", "(click((350,190)), 0)", "(click((190,55)), 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]
    addFat:  ["(swipe_left, 0)", "(swipe_left, 0)", "(click((40,190)), 0)", "(click((40,190)), 0)", "(click((190,55)), 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(swipe_left, 0)", "(click((190,55)), 8)" ]

DuaKhatqmAlQuran:
  package: com.appsforall.duakhatamalquran
  activity: com.appsforall.duakhatamalquran.MainActivityWear
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Endomondo:
  package: com.endomondo.android
  activity: com.endomondo.android.wear.ui.WearAppActivity
  keepOnly: [open, run, browseMap]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    run: ["(click((190,190)), 13)", "(swipe_down, 0)", "(click((190,190)), 0)", "(click((250,250)), 2)"] # "(click((190,190)), 3)"]
    browseMap: ["(swipe_left, 0)", "(scroll_right, 3)", "(scroll_up, 3)", "(scroll_up, 4)", "(scroll_right, 2)"] # "(click((190,190)), 3)"]
    openMap: ["(swipe_left, 20)"]

FindMyPhone:
  package: com.google.android.gms
  activity: com.google.android.gms.mdm.RingMyPhoneActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Fit:
  package: com.google.android.apps.fitness
  activity: com.google.android.wearable.fitness.passive.ui.PassiveActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

FitBreathe:
  package:  com.google.android.apps.fitness
  activity: com.google.android.wearable.fitness.realtime.breathe.BreatheLauncherActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

FitWorkout:
  package:  com.google.android.apps.fitness
  activity: com.google.android.wearable.fitness.realtime.RealtimeActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

FITIVPlus:
  package: com.fitiv.fitivapplication
  activity: com.fitiv.fitivapplication.activities.SplashActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Flashlight:
  package: com.google.android.clockwork.flashlight
  activity: com.google.android.clockwork.flashlight.FlashlightActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


FoursquareCityGuide:
  package:  com.joelapenna.foursquared
  activity: .wearable.MainActivity
  keepOnly: [open, coffee, food, fun, nightlife, shopping]
  actions:
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    openAndClose: ["(open_app, 20)", "(close_app, 5)"]
    food: ["(click((250, 300)), 15)"]
    coffee: ["(click((250, 370)), 15)"]
    nightlife: ["(swipe((250, 370),(250, 50)), 0)", "(click((250, 50)), 15)"]
    fun: ["(swipe((250, 370),(250, 50)), 0)", "(click((250, 150)), 15)"]
    shopping: ["(swipe((250, 370),(250, 50)), 0)", "(swipe((250, 350),(250, 50)), 0)", "(click((250, 350)), 10)"]


Glide:
  package: com.glidetalk.glideapp
  activity: com.glidetalk.glideapp.ThreadListActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

GooglePay:
  package: com.google.android.wearable.app
  activity: com.google.android.clockwork.home.pay.FastPayActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


HealthyRecipes:
  package: com.endless.healthyrecipes
  activity: com.endless.healthyrecipes.HomeActivity
  keepOnly: [researchRecipy]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    researchRecipy: ["(swipe((200, 250),(200, 150)), 0)", "(click((130, 275)), 0)", "(press_deterministic_letters('duck'), 0)", "(click((300, 60)), 15)"]
#  Permission Denial
HeartRate:
  package: com.huawei.health
  activity: com.huawei.bone.view.heartrate.activity.HeartRateMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

KeepNotes:
  package: com.google.android.keep
  activity: com.google.android.keep.wear.MicroBrowseActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Krone:
  package: at.krone
  activity: at.krone.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Lifesum:
  package: com.sillens.shapeupclub
  activity: com.sillens.shapeupclub.onboarding.StartActivity
  keepOnly: [open, addFood, addWater]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force-stop, 20)"]
    addFood: ["(swipe((200, 330),(200, 0)), 0)", "(click((200, 50)), 0)",  "(click((230, 370)), 6)"]
    addWater: ["(swipe((200, 300),(200, 0)), 0)", "(swipe((200, 330),(200, 0)), 0)", "(click((200, 50)), 6)"]

MapMyRun:
  package: com.mapmyrun.android2
  activity: com.mapmyfitness.android.view.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Maps:
  package: com.google.android.apps.maps
  activity: com.google.android.apps.gmmwearable.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Medisafe:
  package: com.medisafe.android.client
  activity: com.medisafe.android.wear.CustomWearableList
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Meduza:
  package: io.meduza.android
  activity: io.meduza.android.RootActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

  # Bank
Mobilis:
  package: br.com.gerenciadorfinanceiro.controller
  activity: br.com.mobills.wear.views.MobillsWearActivity
  keepOnly: [open]
  actions:
    # Open, wait and close
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    addExpense: ["(click((250 50)), 15)", "(,0)"]

Outlook:
  package: com.microsoft.office.outlook
  activity: .activities.HubActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Phone:
  package: com.google.android.apps.wearable.phone
  activity: com.google.android.clockwork.phone.dialer.DialerActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

PlayMusic:
  package: com.google.android.music
  activity: com.google.android.music.wear.ui.HomeActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


PlayStore:
  package: com.android.vending
  activity: com.google.android.finsky.wear.activities.MainActivity
  keepOnly: [open, deterministicBrowse]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    randomBrowse: ["(click((200,20)), 0)", "(click((270, 200)), 0)", "(press_random_letters(), 0)", "(click((300, 30)), 0)"]
    coherentBrowse: []
    deterministicBrowse: [ "(do_nothing, 18)", "(click((200,20)), 0)", "(click((270, 200)), 0)", "(press_deterministic_letters('religious'), 0)", "(click((300, 30)), 8)"]

Qardio:
  package: com.getqardio.android
  activity: com.getqardio.android.wearable.ui.activity.MenuActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Reminders:
  package: com.google.android.googlequicksearchbox
  activity: com.google.android.wearable.reminders.frontend.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Running:
  package: com.runtastic.android
  activity: com.runtastic.android.wear.ui.LaunchActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

SalatTime:
  package: online.makkahtv.salattime
  activity: online.makkahtv.salattime.activity.MainChooseActivity
  keepOnly: [open]
  actions:
    # 1. Open, wait and close
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Shazam:
  package: com.shazam.android
  activity: com.shazam.android.wear.activity.TaggingActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


Sleep:
  package: com.huawei.health
  activity: com.huawei.bone.view.sleep.activity.SleepMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

SleepTracking:
  package: com.urbandroid.sleep
  activity: .wear.Sleep
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

SmokingLog:
  package: com.ccswe.SmokingLog
  activity: com.ccswe.SmokingLog.LauncherActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
    smoke15sec: ["(click((215, 330)), 0)", "(click((215, 170)), 15)", "(click((215, 330)), 5)"]
    refuseToSmoke: []  # Must be played after smoke15sec

SmartZmanim:
  package: com.wyre.zmanim
  activity: com.wyre.zmanim.Activties.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


Spotify:
  package: com.spotify.music
  activity: com.spotify.music.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

# Stopwatch:
#   package: com.google.android.deskclock
#   activity: com.google.android.deskclock.StopwatchActivity
#   keepOnly: [open]  # Action to be selected starting at 1.
#   actions :
#     open: ["(open_app, 20)"]
#     force-stop: ["(force_stop, 20)"]

Strava:
  package: com.strava
  activity: com.strava.WearActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]


Telegram:
  package: org.telegram.messenger
  activity: org.telegram.messenger.wear.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Timer:
  package: com.google.android.deskclock
  activity: com.google.android.deskclock.TimerGatewayActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Translate:
  package: com.google.android.apps.translate
  activity: com.google.android.wearable.translate.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

UARecord:
  package: com.ua.record
  activity: com.ua.record.wear.ui.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

WashPost:
  package: com.washingtonpost.android
  activity: com.wapo.flagship.WearMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

WearCasts:
  package: com.krisdb.wearcasts
  activity: com.krisdb.wearcasts.Activities.MainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Weather:
  package: com.google.android.wearable.app
  activity: com.google.android.clockwork.home.weather.WeatherActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]

Workout:
  package: com.huawei.health
  activity: com.huawei.bone.view.workout.activity.WorkoutMainActivity
  keepOnly: [open]  # Action to be selected starting at 1.
  actions :
    open: ["(open_app, 20)"]
    force-stop: ["(force_stop, 20)"]
