
# Previously analysed
Endomondo:
  package: com.endomondo.android
  activity: com.endomondo.android.wear.ui.WearAppActivity
  actions :
    # open for 1min and close
    - ["(open_app, 120)", "(close_app, 5)"]
    # play for 2min and close
    - ["(open_app, 7)", "(button_click_func((190,190)), 5)", "(swipe_left, 1)", "(close_app, 5)"] # "(button_click_func((190,190)), 3)"]
    # Bowse the map
    - ["(open_app, 7)", "(swipe_right, 3)", "(scroll_right, 3)", "(scroll_up, 3)", "(scroll_up, 4)", "(scroll_right, 2)", "(close_app, 5)"] # "(button_click_func((190,190)), 3)"]


MapMyRun:
  package: com.mapmyrun.android2
  activity: com.mapmyfitness.android.view.MainActivity
  actions:
  # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]

# Religious
Bible of line:
  package: com.bestweatherfor.bibleoffline_pt_ra
  activity: com.bestweatherfor.bibleoffline_pt_ra.MainActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]



Athkar of Prayer:
  package: com.appsforall.athkaralsalah
  activity: com.appsforall.athkaralsalah.MainActivityWear
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]


DCML Radio:
  package: org.dclm.live
  activity: .MainActivity
  actions:
    # open and close
    - ["(open_app, 20)", "(close_app, 5)"]
    # Listen to the radio 10 seconds
    - ["(open_app, 10)", "(button_click_func((95, 190)), 10)", "(button_click_func((285, 190)), 5)", "(close_app, 5)"]

Salah (Prayer) time:
  package: online.makkahtv.salattime
  activity: online.makkahtv.salattime.activity.MainChooseActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]

# Health
Calm:
  package: com.calm.android
  activity: com.calm.android.activities.MainWearActivity

Qardio:
  package: com.getqardio.android
  activity: com.getqardio.android.wearable.ui.activity.MenuActivity

Google fit:
  package: com.google.android.apps.fitness
  activity: com.google.android.wearable.fitness.passive.ui.PassiveActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]

# Bank
Mobillis Budget:
  package: br.com.gerenciadorfinanceiro.controller
  activity: br.com.mobills.wear.views.MobillsWearActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]

ASB Mobile App:
  package: nz.co.asb.asbmobile
  activity: nz.co.asb.wear.MainActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]

# Native
Heart rate:
  package: com.huawei.health
  activity: com.huawei.bone.view.heartrate.activity.HeartRateMainActivity

Daily tracking:
  package : com.huawei.health
  activity: com.huawei.bone.view.dailytrack.activity.DailyTrackMainActivity
  actions:
    # Open, wait and close
    - ["(open_app, 20)", "(close_app, 5)"]
    # Open, scroll down and close
